import "@css/bootstrap.min.css";
import "@css/font-awesome.css";
import "@css/animate.css";
import "@css/magnific-popup.css";
import "@css/meanmenu.css";
import "@css/slick.css";
import "@css/swiper-bundle.min.css";
import "@css/nice-select.css";
import "@css/main.css";
import "./globals.css";
import Preloader from "@/layouts/Preloader";

export const metadata = {
  title: "NetBand - Internet Provider and Broadband TV React NextJS Template",
  description:
    "Generated by netBand - Internet Provider and Broadband TV React NextJS Template",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Preloader />
        {children}</body>
    </html>
  );
}
